# Generated by Django 4.2 on 2023-04-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0010_alter_authtoken_user'),
        ('message', '0005_alter_message_receiver_alter_message_sender'),
        ('register', '0003_rename_picture_customuser_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
